// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Slotik.Data;

#nullable disable

namespace Slotik.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908101736_AddAdminDashboard")]
    partial class AddAdminDashboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Slotik.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MasterId")
                        .HasColumnType("integer");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Slotik.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Slotik.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Київ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Харків"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Одеса"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Дніпро"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Львів"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Запоріжжя"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Кривий Ріг"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Миколаїв"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Маріуполь"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Вінниця"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Херсон"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Полтава"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Чернігів"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Черкаси"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Житомир"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Суми"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Кропивницький"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Кременчук"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Кам'янське"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Чернівці"
                        });
                });

            modelBuilder.Entity("Slotik.Models.DaysOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<int>("MasterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("DaysOff");
                });

            modelBuilder.Entity("Slotik.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Голосіївський"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Дарницький"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Name = "Деснянський"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Name = "Дніпровський"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Name = "Оболонський"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            Name = "Печерський"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 1,
                            Name = "Подільський"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 1,
                            Name = "Святошинський"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 1,
                            Name = "Солом'янський"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 1,
                            Name = "Шевченківський"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 2,
                            Name = "Шевченківський"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 2,
                            Name = "Київський"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 2,
                            Name = "Салтівський"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 2,
                            Name = "Немішлянський"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 2,
                            Name = "Індустріальний"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 2,
                            Name = "Слобідський"
                        },
                        new
                        {
                            Id = 17,
                            CityId = 2,
                            Name = "Основ'янський"
                        },
                        new
                        {
                            Id = 18,
                            CityId = 2,
                            Name = "Новобаварський"
                        },
                        new
                        {
                            Id = 19,
                            CityId = 2,
                            Name = "Холодногірський"
                        },
                        new
                        {
                            Id = 20,
                            CityId = 3,
                            Name = "Київський"
                        },
                        new
                        {
                            Id = 21,
                            CityId = 3,
                            Name = "Пересипський"
                        },
                        new
                        {
                            Id = 22,
                            CityId = 3,
                            Name = "Приморський"
                        },
                        new
                        {
                            Id = 23,
                            CityId = 3,
                            Name = "Хаджибейський"
                        },
                        new
                        {
                            Id = 24,
                            CityId = 4,
                            Name = "Амур-Нижньодніпровський"
                        },
                        new
                        {
                            Id = 25,
                            CityId = 4,
                            Name = "Індустріальний"
                        },
                        new
                        {
                            Id = 26,
                            CityId = 4,
                            Name = "Новокодацький"
                        },
                        new
                        {
                            Id = 27,
                            CityId = 4,
                            Name = "Самарський"
                        },
                        new
                        {
                            Id = 28,
                            CityId = 4,
                            Name = "Соборний"
                        },
                        new
                        {
                            Id = 29,
                            CityId = 4,
                            Name = "Центральний"
                        },
                        new
                        {
                            Id = 30,
                            CityId = 4,
                            Name = "Чечелівський"
                        },
                        new
                        {
                            Id = 31,
                            CityId = 4,
                            Name = "Шевченківський"
                        },
                        new
                        {
                            Id = 32,
                            CityId = 5,
                            Name = "Галицький"
                        },
                        new
                        {
                            Id = 33,
                            CityId = 5,
                            Name = "Залізничний"
                        },
                        new
                        {
                            Id = 34,
                            CityId = 5,
                            Name = "Личаківський"
                        },
                        new
                        {
                            Id = 35,
                            CityId = 5,
                            Name = "Сихівський"
                        },
                        new
                        {
                            Id = 36,
                            CityId = 5,
                            Name = "Франківський"
                        },
                        new
                        {
                            Id = 37,
                            CityId = 5,
                            Name = "Шевченківський"
                        },
                        new
                        {
                            Id = 38,
                            CityId = 6,
                            Name = "Олександрівський"
                        },
                        new
                        {
                            Id = 39,
                            CityId = 6,
                            Name = "Заводський"
                        },
                        new
                        {
                            Id = 40,
                            CityId = 6,
                            Name = "Комунарський"
                        },
                        new
                        {
                            Id = 41,
                            CityId = 6,
                            Name = "Дніпровський"
                        },
                        new
                        {
                            Id = 42,
                            CityId = 6,
                            Name = "Вознесенівський"
                        },
                        new
                        {
                            Id = 43,
                            CityId = 6,
                            Name = "Хортицький"
                        },
                        new
                        {
                            Id = 44,
                            CityId = 6,
                            Name = "Шевченківський"
                        },
                        new
                        {
                            Id = 45,
                            CityId = 7,
                            Name = "Довгинцівський"
                        },
                        new
                        {
                            Id = 46,
                            CityId = 7,
                            Name = "Покровський"
                        },
                        new
                        {
                            Id = 47,
                            CityId = 7,
                            Name = "Інгулецький"
                        },
                        new
                        {
                            Id = 48,
                            CityId = 7,
                            Name = "Металургійний"
                        },
                        new
                        {
                            Id = 49,
                            CityId = 7,
                            Name = "Нікопольський"
                        },
                        new
                        {
                            Id = 50,
                            CityId = 7,
                            Name = "Саксаганський"
                        },
                        new
                        {
                            Id = 51,
                            CityId = 7,
                            Name = "Тернівський"
                        },
                        new
                        {
                            Id = 52,
                            CityId = 7,
                            Name = "Центрально-Міський"
                        },
                        new
                        {
                            Id = 53,
                            CityId = 8,
                            Name = "Заводський"
                        },
                        new
                        {
                            Id = 54,
                            CityId = 8,
                            Name = "Корабельний"
                        },
                        new
                        {
                            Id = 55,
                            CityId = 8,
                            Name = "Інгульський"
                        },
                        new
                        {
                            Id = 56,
                            CityId = 8,
                            Name = "Центральний"
                        },
                        new
                        {
                            Id = 57,
                            CityId = 9,
                            Name = "Кальміуський"
                        },
                        new
                        {
                            Id = 58,
                            CityId = 9,
                            Name = "Лівобережний"
                        },
                        new
                        {
                            Id = 59,
                            CityId = 9,
                            Name = "Приморський"
                        },
                        new
                        {
                            Id = 60,
                            CityId = 9,
                            Name = "Центральний"
                        },
                        new
                        {
                            Id = 61,
                            CityId = 10,
                            Name = "Замостянський"
                        },
                        new
                        {
                            Id = 62,
                            CityId = 10,
                            Name = "Вишенька"
                        },
                        new
                        {
                            Id = 63,
                            CityId = 10,
                            Name = "Центр"
                        },
                        new
                        {
                            Id = 64,
                            CityId = 10,
                            Name = "П'ятничани"
                        },
                        new
                        {
                            Id = 65,
                            CityId = 10,
                            Name = "Сабарів"
                        },
                        new
                        {
                            Id = 66,
                            CityId = 10,
                            Name = "Старе місто"
                        },
                        new
                        {
                            Id = 67,
                            CityId = 11,
                            Name = "Дніпровський"
                        },
                        new
                        {
                            Id = 68,
                            CityId = 11,
                            Name = "Корабельний"
                        },
                        new
                        {
                            Id = 69,
                            CityId = 11,
                            Name = "Суворовський"
                        },
                        new
                        {
                            Id = 70,
                            CityId = 12,
                            Name = "Київський"
                        },
                        new
                        {
                            Id = 71,
                            CityId = 12,
                            Name = "Шевченківський"
                        },
                        new
                        {
                            Id = 72,
                            CityId = 12,
                            Name = "Подільський"
                        },
                        new
                        {
                            Id = 73,
                            CityId = 13,
                            Name = "Деснянський"
                        },
                        new
                        {
                            Id = 74,
                            CityId = 13,
                            Name = "Новозаводський"
                        },
                        new
                        {
                            Id = 75,
                            CityId = 14,
                            Name = "Придніпровський"
                        },
                        new
                        {
                            Id = 76,
                            CityId = 14,
                            Name = "Соснівський"
                        },
                        new
                        {
                            Id = 77,
                            CityId = 15,
                            Name = "Богунський"
                        },
                        new
                        {
                            Id = 78,
                            CityId = 15,
                            Name = "Корольовський"
                        },
                        new
                        {
                            Id = 79,
                            CityId = 16,
                            Name = "Ковпаківський"
                        },
                        new
                        {
                            Id = 80,
                            CityId = 16,
                            Name = "Зарічний"
                        },
                        new
                        {
                            Id = 81,
                            CityId = 17,
                            Name = "Фортечний"
                        },
                        new
                        {
                            Id = 82,
                            CityId = 17,
                            Name = "Подільський"
                        },
                        new
                        {
                            Id = 83,
                            CityId = 18,
                            Name = "Автозаводський"
                        },
                        new
                        {
                            Id = 84,
                            CityId = 18,
                            Name = "Крюківський"
                        },
                        new
                        {
                            Id = 85,
                            CityId = 19,
                            Name = "Дніпровський"
                        },
                        new
                        {
                            Id = 86,
                            CityId = 19,
                            Name = "Заводський"
                        },
                        new
                        {
                            Id = 87,
                            CityId = 19,
                            Name = "Південний"
                        },
                        new
                        {
                            Id = 88,
                            CityId = 20,
                            Name = "Першотравневий"
                        },
                        new
                        {
                            Id = 89,
                            CityId = 20,
                            Name = "Садгірський"
                        },
                        new
                        {
                            Id = 90,
                            CityId = 20,
                            Name = "Шевченківський"
                        });
                });

            modelBuilder.Entity("Slotik.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.HasIndex("UserId", "MasterId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Slotik.Models.Master", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("SlotStepMin")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Masters");
                });

            modelBuilder.Entity("Slotik.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Slotik.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Slotik.Models.PendingRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PendingRegistrations");
                });

            modelBuilder.Entity("Slotik.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Slotik.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("BreakEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("BreakStart")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsWorking")
                        .HasColumnType("boolean");

                    b.Property<int>("MasterId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Weekday")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Slotik.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMin")
                        .HasColumnType("integer");

                    b.Property<string>("Included")
                        .HasColumnType("text");

                    b.Property<int>("MasterId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Slotik.Models.ServicePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServicePhotos");
                });

            modelBuilder.Entity("Slotik.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MasterId")
                        .HasColumnType("integer");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Slotik.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "superadmin@slotik.local",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "d357150517d3e65ae84985f7b705ad99fdc38372a22ecea0cecaf8aaf820a249",
                            Phone = "+380000000000",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Slotik.Models.Booking", b =>
                {
                    b.HasOne("Slotik.Models.Master", "Master")
                        .WithMany("Bookings")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slotik.Models.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slotik.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Slotik.Models.DaysOff", b =>
                {
                    b.HasOne("Slotik.Models.Master", "Master")
                        .WithMany("DaysOff")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("Slotik.Models.District", b =>
                {
                    b.HasOne("Slotik.Models.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Slotik.Models.Favorite", b =>
                {
                    b.HasOne("Slotik.Models.Master", "Master")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slotik.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Slotik.Models.Master", b =>
                {
                    b.HasOne("Slotik.Models.Category", "Category")
                        .WithMany("Masters")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slotik.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Slotik.Models.User", "User")
                        .WithOne("Master")
                        .HasForeignKey("Slotik.Models.Master", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("District");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Slotik.Models.Notification", b =>
                {
                    b.HasOne("Slotik.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Slotik.Models.Payment", b =>
                {
                    b.HasOne("Slotik.Models.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Slotik.Models.Review", b =>
                {
                    b.HasOne("Slotik.Models.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("Slotik.Models.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Slotik.Models.Schedule", b =>
                {
                    b.HasOne("Slotik.Models.Master", "Master")
                        .WithMany("Schedules")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("Slotik.Models.Service", b =>
                {
                    b.HasOne("Slotik.Models.Master", "Master")
                        .WithMany("Services")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("Slotik.Models.ServicePhoto", b =>
                {
                    b.HasOne("Slotik.Models.Service", "Service")
                        .WithMany("Photos")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Slotik.Models.Subscription", b =>
                {
                    b.HasOne("Slotik.Models.Master", "Master")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("Slotik.Models.Booking", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("Slotik.Models.Category", b =>
                {
                    b.Navigation("Masters");
                });

            modelBuilder.Entity("Slotik.Models.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Slotik.Models.Master", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("DaysOff");

                    b.Navigation("FavoritedBy");

                    b.Navigation("Schedules");

                    b.Navigation("Services");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Slotik.Models.Service", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Slotik.Models.Subscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Slotik.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");

                    b.Navigation("Master");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
